services:
  certbot:
    image: certbot/certbot:v2.11.0
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    # command: certonly
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - solutionary-network

networks:
  solutionary-network:
    external: true