services:

  mongo:
    image: mongo:8.0.3
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
    networks:
      - solutionary-network

networks:
  solutionary-network:
    external: true
# networks:
#   solutionary-network:
#     name: solutionary-network
#     driver: bridge
