services:

  mongo:
    image: mongo:8.0.3
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: mongo
        target: /data/db
      - ./mongod.conf:/etc/mongod.conf
    networks:
      - solutionary

volumes:
  mongo:
    name: mongo

networks:
  solutionary:
    external: true